variables:
  S3_BUCKET_NAME: "website-dapp-staging"

deploy to staging:
  environment: staging
  image: node:14
  script:
  - yarn
  - yarn build
  - sudo apt install python3-pip
  - pip3 install awscli
  - aws s3 sync ./out s3://website-dapp-staging
  only:
  - staging
