variables:
  S3_BUCKET_NAME: "website-dapp-staging"

deploy to staging:
  environment: staging
  image: python:latest
  script:
  - yarn
  - yarn build
  - pip install awscli
  - aws s3 sync ./out s3://website-dapp-staging
  only:
  - staging
