variables:
  S3_BUCKET_NAME: "website-dapp-staging"

build-staging:
  environment: staging
  image: node:14
  script:
  - yarn
  - yarn build
  artifacts:
    paths:
      - out  
  only:
    - staging
deploy to s3 staging:
  stage: deploy
  image: 
    name: amazon/aws-cli
    entrypoint: [""]
  script:
    - aws --version
    - aws s3 rm s3://website-dapp-staging --recursive
    - aws s3 sync out s3://website-dapp-staging
  only:
    - staging

build-production:
  environment: production
  image: node:14
  script:
  - yarn
  - yarn build:prod
  artifacts:
    paths:
      - out  
  only:
    - main
sync to s3 production:
  stage: deploy
  image: 
    name: amazon/aws-cli
    entrypoint: [""]
  script:
    - aws --version
    - aws s3 rm s3://website-dapp --recursive
    - aws s3 sync out s3://website-dapp
  only:
    - main
