variables:
  S3_BUCKET_NAME: "website-dapp-staging"

deploy to staging:
  environment: staging
  image: node:14
  script:
  - yarn
  - yarn build
artifacts:
  paths:
    - out  
only:
  - staging
deploy to s3:
  stage: deploy
  image: 
    name: amazon/aws-cli
    entrypoint: [""]
  script:
    - aws --version
    - aws s3 rm s3://website-dapp-staging --recursive
    - aws s3 sync out s3://website-dapp-staging
