stages:
  - dev-build
  - dev-deploy
  - staging-build
  - staging-deploy

.aws_cli_init:
  before_script:
    - |
      yum install -y jq

dev-build:
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
  image: node:14
  stage: dev-build
  script:
    - yarn add next react react-dom
    - yarn build:dev
  artifacts:
    paths:
      - out-dev

dev-deploy:
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  services:
    - docker:dind
  stage: dev-deploy
  extends:
    - .aws_cli_init
  script:
    - |
      ./scripts/assume_deployer_role.sh $account

      # TODO:
      ./scripts/deploy_to_s3.sh $bucket_name $artifacts_folder $cloudfront_id
  variables:
    account: myria-net-nonprod
    region: us-east-1
    bucket_name: myria-dev.nonprod-myria.com
    artifacts_folder: out-dev
    cloudfront_id: E16CH11X42OZD4
  dependencies:
    - dev-build

staging-build:
  # rules:
  #   - if: '$CI_COMMIT_BRANCH == "staging"'
  image: node:14
  stage: staging-build
  script:
    - yarn add next react react-dom
    - yarn build:staging
  artifacts:
    paths:
      - out-staging

staging-deploy:
  # rules:
  #   - if: '$CI_COMMIT_BRANCH == "staging"'
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  services:
    - docker:dind
  stage: staging-deploy
  extends:
    - .aws_cli_init
  script:
    - |
      ./scripts/assume_deployer_role.sh $account

      # TODO:
      ./scripts/deploy_to_s3.sh $bucket_name $artifacts_folder $cloudfront_id
  variables:
    account: myria-net-nonprod
    region: us-east-1
    bucket_name: myria-staging.nonprod-myria.com
    artifacts_folder: out-staging
    cloudfront_id: E13LZBS3DMRA8F
  dependencies:
    - staging-build

# The below is legacy using the previous manually created bucket
staging-legacy-deploy:
  # rules:
  #   - if: '$CI_COMMIT_BRANCH == "staging"'
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  services:
    - docker:dind
  stage: staging-deploy
  extends:
    - .aws_cli_init
  script:
    - |
      ./scripts/assume_deployer_role.sh $account

      # TODO:
      ./scripts/deploy_to_s3.sh $bucket_name $artifacts_folder $cloudfront_id
  variables:
    account: myria-net-prod
    region: us-east-1
    bucket_name: website-dapp-staging
    artifacts_folder: out-staging
    cloudfront_id: E36R51175D7RC5
  dependencies:
    - staging-build
