stages:
  - dev-build
  - dev-deploy
  # - staging
  # - preprod
  # - prod

.aws_cli_init:
  before_script:
    - |
      yum install -y jq

dev-build:
  # rules:
  #   - if: '$CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "staging"'
  image: node:14
  stage: dev-build
  script:
    - yarn add next react react-dom
    - yarn build:dev
  artifacts:
    paths:
      - out-dev # Note: Might need to change to out-dev, otherwise might conflicts with staging steps?

dev-deploy:
  # rules:
  #   - if: '$CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "staging"'
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  services:
    - docker:dind
  stage: dev-deploy
  extends:
    - .aws_cli_init
  script:
    - |
      ./scripts/assume_deployer_role.sh $account

      # TODO:
      # ./scripts/deploy_to_s3.sh $bucket_name $artifacts_folder
      # ./scripts/invalidate_cdn.sh $cloudfront_id
  variables:
    account: myria-net-nonprod
    region: us-east-1
    bucket_name: dev
    artifacts_folder: out-dev
    cloudfront_id: from-s3-bucket # The cloudfront id of this env
  dependencies:
    - dev-build
