import { Trans } from '@lingui/macro';
import Modal from 'src/components/Modal';
import Input from 'src/components/Input';
import React from 'react';
import Button from 'src/components/core/Button';

const TermsOfServiceModal = ({
  open,
  onClose,
  onAgree
}: {
  open: boolean;
  onClose?: () => void;
  onAgree?: () => void;
}) => {
  const [agree, setAgree] = React.useState(false);

  return (
    <Modal open={open} onOpenChange={onClose}>
      <Modal.Content
        title="Future node purchase agreement"
        className="z-20 shadow-[0_0_40px_10px_#0000004D] md:max-w-[832px]">
        <div className="py-8">
          <div className="overflow-y-auto h-72 px-8">
            <p className="mb-6">
              <Trans>
                THIS FUTURE NODE PURCHASE AGREEMENT HAS NOT BEEN REGISTERED UNDER THE SECURITIES
                LAWS OF ANY JURISDICTION. THIS AGREEMENT MAY NOT BE OFFERED, SOLD OR OTHERWISE
                TRANSFERRED, ASSIGNED, PLEDGED OR HYPOTHECATED EXCEPT (I) AS PERMITTED HEREUNDER,
                AND (II) UNDER APPLICABLE LAW PURSUANT TO AN EFFECTIVE REGISTRATION STATEMENT OR AN
                EXEMPTION THEREFROM. NEW OR CHANGING LAWS AND REGULATIONS OR INTERPRETATIONS OF
                EXISTING LAWS AND REGULATIONS, IN THE BRITISH VIRGIN ISLANDS AND IN OTHER
                JURISDICTIONS, MAY MATERIALLY AND ADVERSELY IMPACT THE VIABILITY OF THE PLATFORM,
                THE VALUE OF THE NODES AND THE TOKENS TO BE GENERATED BY SUCH NODES, THE LIQUIDITY
                OF SUCH TOKENS AND THE STRUCTURE, RIGHTS AND TRANSFERABILITY OF SUCH TOKENS.
                PARTICIPATION IN THE OFFERING INVOLVES A HIGH DEGREE OF RISKS. YOU SHOULD CAREFULLY
                REVIEW THE CONFIDENTIAL INFORMATION MATERIALS PROVIDED TO YOU IN CONNECTION
                HEREWITH, TOGETHER WITH ALL THE OTHER INFORMATION CONTAINED IN THIS AGREEMENT,
                BEFORE MAKING A PURCHASE DECISION. OWNERSHIP OF A NODE DOES NOT REPRESENT OR
                CONSTITUTE ANY OWNERSHIP RIGHT OR STAKE, SHARE OR SECURITY, DEBT OR EQUIVALENT
                RIGHT, OR ANY RIGHT TO RECEIVE ANY FUTURE REVENUE OR FORM OF PARTICIPATION IN OR
                RELATING TO ANY BLOCKCHAIN OR DIGITAL REWARD, INCLUDING IN CONNECTION WITH THE
                PLATFORM.
              </Trans>
            </p>
            <p className="text-center">
              <Trans>FUTURE NODE PURCHASE AGREEMENT</Trans>
            </p>
            <p className="text-center">
              <Trans>OF</Trans>
            </p>
            <p className="text-center">
              <Trans>METAGALACTIC JUMP LTD.</Trans>
            </p>
            <p className="text-center">
              <Trans>a British Virgin Islands business company with limited liability</Trans>
            </p>
          </div>
          <div className="pl-8 pt-4 flex">
            <Input
              type="checkbox"
              checked={agree}
              onChange={(e) => setAgree(e.currentTarget.checked)}
            />
            <p className="ml-4">
              <Trans>Agree and sign</Trans>
            </p>
          </div>
          <div className="flex w-full justify-end pr-8">
            <Button
              className="btn-lg btn-primary justify-end px-10"
              disabled={!agree}
              onClick={onAgree}>
              <Trans>Accept</Trans>
            </Button>
          </div>
        </div>
      </Modal.Content>
    </Modal>
  );
};

export default TermsOfServiceModal;
